In [1]:
# numpy é um biblioteca de algebra linear para Python

In [2]:
import numpy as np

In [3]:
minha_lista = [1, 2, 3]
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [11]:
arr = np.zeros((5, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
arr = np.ones((5, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
np.random.rand(5)

array([0.43107162, 0.17099235, 0.3503161 , 0.65091668, 0.25920266])

In [16]:
np.random.rand(5) * 100

array([61.46447819, 47.27219222, 83.90966731, 54.24458635, 26.55424433])

In [17]:
np.random.rand(5, 4, 3)

array([[[0.09525708, 0.36504379, 0.1012539 ],
        [0.71527926, 0.25004335, 0.87163176],
        [0.99616459, 0.31022562, 0.93343786],
        [0.65112231, 0.84149956, 0.27175417]],

       [[0.65862752, 0.88538353, 0.97666664],
        [0.35929211, 0.38884743, 0.46460789],
        [0.54528983, 0.05988774, 0.25667447],
        [0.09366524, 0.33344801, 0.90962144]],

       [[0.07248725, 0.294083  , 0.1830189 ],
        [0.63970996, 0.23154552, 0.97371231],
        [0.6976125 , 0.10980826, 0.64999433],
        [0.49407527, 0.73934713, 0.13608083]],

       [[0.14784039, 0.53192173, 0.71206439],
        [0.21307095, 0.85468531, 0.49845475],
        [0.23586416, 0.14230377, 0.78733965],
        [0.04309115, 0.96087304, 0.98446252]],

       [[0.54646182, 0.43612838, 0.11093057],
        [0.73985261, 0.21804332, 0.30270045],
        [0.60930343, 0.34764053, 0.39844189],
        [0.48122547, 0.22862131, 0.85223696]]])

In [18]:
np.random.randn(4)

array([ 0.20805276,  0.46718652,  0.26644438, -1.25387448])

In [19]:
np.random.randint(0, 100, 10)

array([34, 28, 23, 95, 56, 41, 47, 55,  1, 98])

In [20]:
arr = np.random.rand(35)
arr

array([0.56618035, 0.09044195, 0.10642118, 0.66094732, 0.47530242,
       0.1631737 , 0.63344987, 0.41472651, 0.3036889 , 0.40070126,
       0.71244547, 0.12865445, 0.11900809, 0.84706495, 0.09322056,
       0.14012132, 0.84209212, 0.31193964, 0.58136288, 0.59445815,
       0.01156652, 0.39881141, 0.05120151, 0.31360869, 0.6908813 ,
       0.22603085, 0.88250286, 0.277082  , 0.86300974, 0.32430819,
       0.33727851, 0.64663915, 0.09004028, 0.73924097, 0.92110926])

In [21]:
arr.reshape(5, 7)

array([[0.56618035, 0.09044195, 0.10642118, 0.66094732, 0.47530242,
        0.1631737 , 0.63344987],
       [0.41472651, 0.3036889 , 0.40070126, 0.71244547, 0.12865445,
        0.11900809, 0.84706495],
       [0.09322056, 0.14012132, 0.84209212, 0.31193964, 0.58136288,
        0.59445815, 0.01156652],
       [0.39881141, 0.05120151, 0.31360869, 0.6908813 , 0.22603085,
        0.88250286, 0.277082  ],
       [0.86300974, 0.32430819, 0.33727851, 0.64663915, 0.09004028,
        0.73924097, 0.92110926]])

In [22]:
arr = arr.reshape(5, 7)

In [23]:
arr

array([[0.56618035, 0.09044195, 0.10642118, 0.66094732, 0.47530242,
        0.1631737 , 0.63344987],
       [0.41472651, 0.3036889 , 0.40070126, 0.71244547, 0.12865445,
        0.11900809, 0.84706495],
       [0.09322056, 0.14012132, 0.84209212, 0.31193964, 0.58136288,
        0.59445815, 0.01156652],
       [0.39881141, 0.05120151, 0.31360869, 0.6908813 , 0.22603085,
        0.88250286, 0.277082  ],
       [0.86300974, 0.32430819, 0.33727851, 0.64663915, 0.09004028,
        0.73924097, 0.92110926]])

In [24]:
arr.shape

(5, 7)

In [25]:
arr.max()

0.9211092619918966

In [26]:
arr.min()

0.011566519386475016

In [27]:
arr.argmax()

34

In [28]:
arr.argmin()

20

In [29]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [30]:
arr[3]

9

In [31]:
arr[2:5]

array([ 6,  9, 12])

In [32]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [33]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [34]:
arr[2:] = 100
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [35]:
arr = np.arange(0, 50).reshape((5, 10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [36]:
arr.shape

(5, 10)

In [37]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
arr2 = arr[:3].copy()

In [39]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [40]:
arr2[:] = 100

In [41]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [42]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [43]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [44]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
boole = arr > 15

In [46]:
arr[boole]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
arr = np.arange(0, 16)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [50]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [52]:
arr / arr

C:\Users\marco\AppData\Local\Temp\ipykernel_4244\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [54]:
1 / arr

C:\Users\marco\AppData\Local\Temp\ipykernel_4244\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [55]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [56]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [57]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [60]:
np.mean(arr)

7.5

In [61]:
np.std(arr)

4.6097722286464435

In [62]:
np.max(arr)
np.min(arr)

0

In [63]:
#Exercicios Numpy

In [64]:
# Criar um matrix de 10 zeros
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
# criar uma matriz de 10 ones
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
# criar uma matriz de 10 cincos
arr = np.ones(10) * 5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [70]:
# criar uma matriz de inteiros de 10 até 50
arr = np.arange(10, 51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [72]:
# Crie um array dos numeros pares de 10 até 50
arr = np.arange(10, 51, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [76]:
# Criei uma matriz 3x3 com valores variando de 0 até 8]
matriz = np.arange(0, 9).reshape(3, 3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
# Crie uma matriz identidade 3x3
matriz_identidade = np.eye(3)
matriz_identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
# Use NumPy para gerar números aleatórios entre 0 e 1
np.random.rand(1)

array([0.65397711])

In [87]:
# Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.
np.random.normal(size=25)

array([ 0.27174667,  0.39882309,  0.53348613, -2.41370626, -0.5062127 ,
       -0.80585118, -0.81692044, -1.03519899, -2.05812855, -0.73625515,
        0.43090945,  0.07109024,  1.43135182,  0.27332272,  0.62885598,
        0.15185563,  0.3490891 , -2.3769862 ,  1.26617574,  0.33278753,
        1.14850674,  2.06875927, -1.24552353, -1.07684725, -0.55268069])

In [91]:
# crie um matriz que comece 0.01 e vai até 1
matriz = np.arange(1, 101).reshape(10, 10) / 100
matriz

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [95]:
# Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [96]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [114]:
# reproza essa saida
#array([[12, 13, 14, 15],
#      [17, 18, 19, 20],
#       [22, 23, 24, 25]])
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [134]:
# reproza essa saida: 20
mat[3,4]

20

In [141]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SEJA
# array([[ 2],
#        [ 7],
#        [12]])


mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [144]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SEJA
# array([21, 22, 23, 24, 25])
mat[4:]

array([[21, 22, 23, 24, 25]])

In [145]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SEJA
# array([[16, 17, 18, 19, 20],
#       [21, 22, 23, 24, 25]])
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [146]:
# Obter a soma de todos os valores no "mat" = 325 
mat.sum()

325

In [148]:
# Obter o desvio padrão dos valores em mat --> 7.2111025509279782
mat.std()

7.211102550927978

In [149]:
# Obter a soma de todas as colunas em mat  ---> array([55, 60, 65, 70, 75])
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.sum()[]